SELECT TOP (1000) [Continent]
      ,[Country_or_State]
      ,[Province_or_City]
  FROM [dimtables].[dbo].[dim_location]

  SELECT * FROM [dimtables].[dbo].[dim_channel]
  SELECT * FROM [dimtables].[dbo].[dim_customer_details]
  SELECT * FROM [dimtables].[dbo].[dim_date]
  SELECT * FROM [dimtables].[dbo].[dim_location]
  SELECT * FROM [dimtables].[dbo].[dim_payment_id]
  SELECT * FROM [dimtables].[dbo].[dim_pc_product]
  SELECT * FROM [dimtables].[dbo].[dim_priority]
  SELECT * FROM [dimtables].[dbo].[dim_sales_person]
  SELECT * FROM [dimtables].[dbo].[dim_shop]
  SELECT * FROM [dimtables].[dbo].[pc_sales_fact]